unit TestUProductDescription;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, UItemID, UProductDescription, UMoney;

type
  // Test methods for class TProductDescription

  TestTProductDescription = class(TTestCase)
  strict private
    FProductDescription: TProductDescription;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  end;

implementation

procedure TestTProductDescription.SetUp;
begin
  FProductDescription := TProductDescription.Create;
end;

procedure TestTProductDescription.TearDown;
begin
  FProductDescription.Free;
  FProductDescription := nil;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTProductDescription.Suite);
end.

