unit TestUProductCatalog;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Generics.Defaults, UProductDescription, Generics.Collections,
  SysUtils, UProductCatalog, UMoney, UItemID;

type
  // Test methods for class TProductCatalog

  TestTProductCatalog = class(TTestCase)
  strict private
    FProductCatalog: TProductCatalog;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  end;

implementation

procedure TestTProductCatalog.SetUp;
begin
  FProductCatalog := TProductCatalog.Create;
end;

procedure TestTProductCatalog.TearDown;
begin
  FProductCatalog.Free;
  FProductCatalog := nil;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTProductCatalog.Suite);
end.

