unit TestUSale;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Generics.Defaults, UPayment, UProductDescription, USale, SysUtils,
  UMoney, USalesLineItem, Generics.Collections;

type
  // Test methods for class TSale

  TestTSale = class(TTestCase)
  strict private
    FSale: TSale;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  end;

implementation

procedure TestTSale.SetUp;
begin
  FSale := TSale.Create;
end;

procedure TestTSale.TearDown;
begin
  FSale.Free;
  FSale := nil;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTSale.Suite);
end.

