unit TestUSalesLineItem;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, UProductDescription, UMoney, USalesLineItem;

type
  // Test methods for class TSalesLineItem

  TestTSalesLineItem = class(TTestCase)
  strict private
    FSalesLineItem: TSalesLineItem;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  end;

implementation

procedure TestTSalesLineItem.SetUp;
begin
  FSalesLineItem := TSalesLineItem.Create;
end;

procedure TestTSalesLineItem.TearDown;
begin
  FSalesLineItem.Free;
  FSalesLineItem := nil;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTSalesLineItem.Suite);
end.

