unit TestUDie;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, UDie;

type
  // Test methods for class TDie

  TestTDie = class(TTestCase)
  strict private
    FDie: TDie;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  end;

implementation

procedure TestTDie.SetUp;
begin
  FDie := TDie.Create;
end;

procedure TestTDie.TearDown;
begin
  FDie.Free;
  FDie := nil;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTDie.Suite);
end.

