unit TestUMGame;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, UMGame, Generics.Defaults, Generics.Collections, UPlayer, UDie, Classes,
  SysUtils, UBoard;

type
  // Test methods for class TMGame

  TestTMGame = class(TTestCase)
  strict private
    FMGame: TMGame;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  end;

implementation

procedure TestTMGame.SetUp;
begin
  FMGame := TMGame.Create;
end;

procedure TestTMGame.TearDown;
begin
  FMGame.Free;
  FMGame := nil;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTMGame.Suite);
end.

