unit TestUBoard;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Generics.Defaults, Generics.Collections, Classes, SysUtils, USquare,
  UBoard;

type
  // Test methods for class TBoard

  TestTBoard = class(TTestCase)
  strict private
    FBoard: TBoard;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  end;

implementation

procedure TestTBoard.SetUp;
begin
  FBoard := TBoard.Create;
end;

procedure TestTBoard.TearDown;
begin
  FBoard.Free;
  FBoard := nil;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTBoard.Suite);
end.

