unit TestUSquare;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, USquare;

type
  // Test methods for class TSquare

  TestTSquare = class(TTestCase)
  strict private
    FSquare: TSquare;
    index: integer;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  end;

implementation

procedure TestTSquare.SetUp;
begin
  FSquare := TSquare.Create(name,index);
end;

procedure TestTSquare.TearDown;
begin
  FSquare.Free;
  FSquare := nil;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTSquare.Suite);
end.

